### ISSUE TITLE
Team rename option doesn't work

### ISSUE THREAD

**Issue by Mauri-atR** [jklick-so/so4t_interactions#1]
the --team-rename option doesn't work because a wrong call to `get_user_data` .
You should change line 86 of so4t_interactions.py 
from:
`users = get_user_data(scraper, client, team_rename=True)`
to:
`users = get_user_data(scraper, client, team_rename=team_rename)`

**Comment by jklick-so** [comment]
@Mauri-atR - Thank you for reporting this! I apologize for the delayed response.

Were you able to workaround the issue by changing that line? 

There are some updates to the API coming this month and I'll be making some updates to this project. I'll roll your fix into that release.

**Comment by jklick-so** [comment]
This fix has been implemented in v1.1, which has now been merged with the main branch. Thank you for your help!
